name: Configure AWS Workflow reusable 3

on:
  workflow_call:

jobs:
  aws-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::123456789012:role/DemoRole
